### ISSUE TITLE
Verify Transaction

### ISSUE THREAD

**Issue by meshboy** [kehers/paystack#17]
The reference code is not being recognized on the verify method 

  /*
  Verify transaction
  */
  verify: {
      method: 'get',
      endpoint: [root, '/verify/{reference}'].join(''),
      args: ['reference']
    },

Please check this method .

**Comment by Subomi** [comment]
What error message do you get sir? 
Please post more information about the situation.

**Comment by FeezyHendrix** [comment]
Hi I keep getting this error anytime I try to verify a transaction. which was successful on paystack dashboard  { status: false, message: 'Transaction reference not found' }
Thanks

**Comment by abu-hasib** [comment]
please am having the same issue, same response:

{ status: false, message: 'Transaction reference not found' }

i have contacted paystack, told me it is the package issue. Did the url change?
