### ISSUE TITLE
Provide helper for handling Paystack events.

### ISSUE THREAD

**Issue by habbes** [kehers/paystack#20]
I think the library should provide an easy way for handling Paystack events. I'd propose something like an express middleware that allows the user to define handlers for the different events, the middleware should also verify the signature before calling the event handler.

Here's an example of what it could look like in practice:

```javascript
const paystack = require('paystack')('secret_key');

const events = paystack.events();

// register handler for different events
events.setHandler('charge.success', (req, res) => {
    const event = req.body;
    // handle event
    res.send(200);
});

// register as express middleware
app.use('/my/webhook/url', events);
```

That's just a suggestion to illustrate the general idea, it doesn't have to be exactly as that. For instance the handler could just receive the event body and a callback or return a promise.

**Comment by Subomi** [comment]
Yes ... very cool bro, I thought of this recently, you can start working on something on a branch.

**Comment by olyjosh** [comment]
Is any body working on this currently

**Comment by Subomi** [comment]
Yes,  I have something, but have been wondering how to really work with it .. Lets take a look at https://gist.github.com/Subomi/2f67c79ed358afef07f1fc20097acb22

**Comment by pariola** [comment]
I recently published a package that takes care of Events [Paystack-API](https://github.com/pariola/paystack).
