### ISSUE TITLE
Npm Library Outdated

### ISSUE THREAD

**Issue by kingstuffy** [kehers/paystack#21]
Npm library has a version of `1.4.1` while the master branch on github has one of `2.0.1`

**Comment by subomi** [comment]
Will be updated asap man. sorry.

**Comment by ibrahimlawal** [comment]
@kehers @Subomi any luck ensuring version on NPM stays in sync with most recent updates?

**Comment by subomi** [comment]
Working on stable fix to that issue bro. Synchronization will be faster soon.

**Comment by ibrahimlawal** [comment]
@Subomi I understand the need to have a stable fix... but you do know the latest on npm is still at 1.4.1 and to use your latest updates, one has to override manually. Ensuring it's at 2.0.1 would be a great first step @kingstuffy @kehers see: https://www.npmjs.com/package/paystack

**Comment by kehers** [comment]
@ibrahimlawal @kingstuffy Sorry for the delay. The npm version has been updated to the latest version.
