### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by timolinn** [kehers/paystack#34]
TypeScript is unable to resolve the package from node_modules.

This is my code
```typescript
import * as paystack from "paystack";
```
I get the following error
```
Could not find a declaration file for module 'paystack'. 'c:/Users/timolin/.../node_modules/paystack/index.js' implicitly has an 'any' type.
```

I can get around this by creating a `paystack.d.ts` inside my secondary `@types` directory, but I don't get auto-completion.

Please is there any plans to add TypeScript support?

**Comment by Oluwatemilorun** [comment]
I think it's better to just use the paystack api as found [here](https://developers.paystack.co/reference)

`var request = require("request");

var options = { method: 'PUT',
  url: 'https://api.paystack.co/integration/payment_session_timeout' };

request(options, function (error, response, body) {
  if (error) throw new Error(error);

  console.log(body);
});`

**Comment by solomon-os** [comment]
Typescript support has been added.

If you need typescript intellisense install the typed package

npm install @types/paystack
