### ISSUE TITLE
Logical reason

### ISSUE THREAD

**Issue by makinyelure** [kehers/paystack#35]
https://github.com/kehers/paystack/blob/e74305a85d3c11c767e24abd96ba96f061f4cc2a/index.js#L27

Am just curious, is this an attempt to create a singleton? I tried finding the purpose of returning an instance of probably already created object but could not justify it

**Comment by timolinn** [comment]
I had similar question when I looked at the code earlier. It doesn't look like a singleton to me. From my experience singletons are usually implemented using static properties and static methods. 

I think what's happening there is between calling the function as a normal function call:
```javascript
const paystack = Paystack(key);
```
And initializing it as you would a class:
```javascript
const paystack = new Paystack(key);
```
it seems to me that the author is trying to enforce the latter usage even if you try to use it as the former.

**Comment by makinyelure** [comment]
@timolinn Can't we use an IIFE for that as in
`var PayStack = ((key) => {
return {
// public API's
}
}(key)`

Am just curious. Could it achieve the same thingy as modular design approach?

**Comment by timolinn** [comment]
@makinyelure Probably!

However, the reason for IIFEs are mostly to prevent global scope pollution, so it's mostly browser related stuff. Nodejs uses modules to guard you from global scope pollution, if you're doing it right, there's no need for IIFEs.

**Comment by makinyelure** [comment]
I don't agree though but I see the point. Thanks
