### ISSUE TITLE
Is this still maintained? 

### ISSUE THREAD

**Issue by rohithzr** [kehers/paystack#38]
I am seeing multiple PRs and Issues. I will be starting to use this library for a client.
@kehers, if you need any help in maintaining this, I'll be happy to maintain this for you.
If you are not interested in maintaining this anymore, or you don't have time enough. I'll fork this. 

Let me know your thoughts. Feel free to reach out.
Twitter: @rohithzr
Mail: rohithzr@live.com

**Comment by subomi** [comment]
Hi @Rohithzr 

Sorry about the delay in response, I should be maintaining this library, but I have been away from JS for sometime, and not actively using it. However, I hope to start working on it, to fix all issues, and bring it up to date in the coming weeks. 

Please let me know how your timing as to when exactly you will be needing this library in your project. So I can work towards it. 

Thanks

**Comment by rohithzr** [comment]
@Subomi so I'll be using it (most probably, within the next week). Wherever I can, will make a PR and hope for a good collaboration at that point. I appreciate your efforts.
